baseURL = "http://insideoutaerials.com/"
languageCode = 'en-us'
title = 'Inside Out Aerials'
# theme = "port-hugo"
theme = "hugo-split-theme"

favicon = "static/favicon.ico"

[[params.visual.image]]
  # enable = true
  file = "static/background.jpg"
  # position = "center center"

[params.visual.video]
  mute = true
  file = "static/ab.mp4"
  # youtubeId = "dk9uNWPP7EA"

# Links List #1
[[params.links]]
  [params.links.list1]
    # heading = "Connect"

    # [[params.links.list1.link]]
    #   text = "Blog"
    #   url = "#"
    #   new_tab = true # new tab

    [[params.links.list1.link]]
      text = "Email"
      url = "mailto:insideoutaerials@gmail.com"
      new_tab = true # Default, open at same tab

    # [[params.links.list1.link]]
    #   text = "Newsletter"
    #   url = "#"
    #   new_tab = true

# Links List #2
[[params.links]]
  [params.links.list2]
    # heading = "Socials"

    [[params.links.list2.link]]
      text = "LinkedIn"
      url = "https://www.linkedin.com/company/inside-out-aerials"
      new_tab = true # new tab

    # [[params.links.list2.link]]
    #   text = "YouTube"
    #   url = "https://www.youtube.com/@Inside_Out_Aerials"
    #   new_tab = true # Default, open at same tab

    # [[params.links.list2.link]]
    #   text = "Space Filler"
    #   url = "#"
    #   new_tab = true

# Links List #3
[[params.links]]
  [params.links.list3]
    # heading = "Connect"

    # [[params.links.list3.link]]
    #   text = "Blog"
    #   url = "#"
    #   new_tab = true # new tab

    [[params.links.list3.link]]
      text = "YouTube"
      url = "https://www.youtube.com/@Inside_Out_Aerials"
      new_tab = true # Default, open at same tab

    # [[params.links.list3.link]]
    #   text = "Newsletter"
    #   url = "#"
    #   new_tab = true



copyright = "&copy;2024 Inside Out Aerials"

